FROM golang:1.16.4-alpine

RUN apk add curl

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin


WORKDIR /opt/app


COPY . .

CMD air -c .air.conf
